version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "19"
    python: "3.10"

python:
  install:
    - requirements: docs/en/requirements.txt

sphinx:
  configuration: docs/en/source/conf.py

formats: all